# Custom Language File for Launcher Customizer

[ejs.app]
title = "0ZONE Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/0-bird/0ZONE"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/R6n3D3UT"

[ejs.settings]
sourceGithubLink = "https://github.com/0-bird/0ZONE"
supportLink = "https://github.com/0-bird/0ZONE/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO 0ZONE"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
